let ToolList = {
  'layer': [{
    name: 'reader',
    iconName: '#icon-bstation',
    label: '显示/隐藏分站',
    cont: '分站',
    class: ''
  }, {
    name: 'traffic_lights',
    iconName: '#icon-traffic-light',
    label: '显示/隐藏红绿灯',
    cont: '红绿灯',
    class: ''
  }, {
    name: 'camera',
    iconName: '#icon-camera',
    label: '显示/隐藏摄像头',
    cont: '摄像头',
    class: ''
  }, {
    name: 'area',
    iconName: '#icon-area',
    label: '显示/隐藏区域',
    cont: '区域',
    class: ''
  }, {
    name: 'landmarker',
    iconName: '#icon-landmarker',
    label: '显示/隐藏地标',
    cont: '地标',
    class: ''
  }, {
    name: 'gas',
    iconName: '#icon-gas',
    label: '显示/隐藏瓦斯',
    cont: '气体数据',
    class: ''
  }, {
    name: 'wind',
    iconName: '#icon-wind',
    label: '显示/隐藏通风数据',
    cont: '通风数据',
    class: ''
  }, {
    name: 'temperature',
    iconName: '#icon-temperature',
    label: '显示/隐藏温度数据',
    cont: '温度数据',
    class: ''
  }, {
    name: 'bzlx_hz',
    class: 'bzlx_hz',
    iconName: '#icon-fire-hedging',
    label: '火灾避灾路线',
    cont: '火灾避灾路线'
  }, {
    name: 'bzlx_sz',
    class: 'bzlx_sz',
    iconName: '#icon-water-hedging',
    label: '水灾避灾路线',
    cont: '水灾避灾路线'
  }, {
    name: 'reset',
    iconName: '#icon-self-adaption',
    label: '实际大小',
    cont: '全图',
    class: ''
  }],
  'search': [{
    name: 'rect_query_vehicle',
    class: 'rect_query_vehicle',
    iconName: '#icon-geometry-vehicle',
    label: '矩形查车',
    cont: '矩形查车'
  }, {
    name: 'circle_query_vehicle',
    class: 'circle_query_vehicle',
    iconName: '#icon-circle-vehicle',
    label: '圆形查车',
    cont: '圆形查车'
  }, {
    name: 'poly_query_vehicle',
    class: 'poly_query_vehicle',
    iconName: '#icon-draw-polygon-vehicle',
    label: '多边形查车',
    cont: '多边形查车'
  }, {
    name: 'rect_query_staff',
    class: 'rect_query_staff',
    iconName: '#icon-geometry-staff',
    label: '矩形查人',
    cont: '矩形查人'
  }, {
    name: 'circle_query_staff',
    class: 'circle_query_staff',
    iconName: '#icon-circle-staff',
    label: '圆形查人',
    cont: '圆形查人'
  }, {
    name: 'poly_query_staff',
    class: 'poly_query_staff',
    iconName: '#icon-draw-polygon-staff',
    label: '多边形查人',
    cont: '多边形查人'
  }],
  'measure': [{
    name: 'measure_length',
    class: 'measure-length',
    iconName: '#icon-measure',
    label: '长度',
    cont: '长度'
  }, {
    name: 'measure_area',
    class: 'measure-area',
    iconName: '#icon-acreage',
    label: '面积',
    cont: '面积'
  }, {
    name: 'edit_area',
    class: 'measure-area',
    iconName: '#icon-edit-area',
    label: '编辑区域',
    cont: '编辑区域'
  }, {
    name: 'edit_landmark',
    class: 'measure-area',
    iconName: '#icon-edit-land',
    label: '编辑地标',
    cont: '编辑地标'
  }]
}

export { ToolList }
